In [1]:
import numpy as np

In [2]:
import scipy as sc

In [3]:
from scipy.linalg import solve

In [44]:
A = np.array (
    [

        [3, 2, 1],

        [5, 5, 5],
        
        [11, 12, 13]

     ]

)

In [45]:
print(A)

[[ 3  2  1]
 [ 5  5  5]
 [11 12 13]]


In [50]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).reshape((3, 3))

In [51]:
print (b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
x = solve(A, b)

<ipython-input-52-3dfcb5577174>:1: LinAlgWarning: Ill-conditioned matrix (rcond=5.95711e-18): result may not be accurate.
  x = solve(A, b)
